---
- name: Check if the worker node is already part of the cluster
  delegate_to: "{{ groups['master'][0] }}"
  shell: kubectl get nodes -o jsonpath='{.items[?(@.metadata.name=="{{ inventory_hostname }}")].metadata.name}'
  register: k8s_worker_node
  ignore_errors: true
  changed_when: false

- name: Join Kubernetes worker to the cluster
  command: sudo {{ hostvars[groups['masters'][0]]['kubeadm_join_command'] }}
  when: k8s_worker_node.stdout != inventory_hostname
