---
- name: Join Kubernetes worker to the cluster
  command: kubeadm join --token {{ hostvars['master']['kubeadm_join_token'] }} {{ hostvars['master']['ansible_host'] }}:6443 --discovery-token-ca-cert-hash sha
