---
- name: Check if kubelet.conf file exists
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Join Kubernetes worker to the cluster
  command: sudo {{ hostvars[groups['masters'][0]]['kubeadm_join_command'] }}
  when: not kubelet_conf.stat.exists

