---
- name: Initialize Kubernetes cluster
  command: >
    sudo kubeadm init --pod-network-cidr=192.168.0.0/16 \
    --apiserver-advertise-address={{ ansible_default_ipv4.address }} \
    --control-plane-endpoint={{ ansible_default_ipv4.address }} \
    --apiserver-cert-extra-sans={{ ansible_default_ipv4.address }}

- name: Create .kube directory
  become: yes
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory

- name: Remove existing Kubernetes config
  become: yes
  file:
    path: "{{ ansible_env.HOME }}/.kube/config"
    state: absent

- name: Copy admin.conf to .kube directory
  become: yes
  command: >
    cp -i /etc/kubernetes/admin.conf {{ ansible_env.HOME }}/.kube/config

- name: Change ownership of Kubernetes config
  become: yes
  command: >
    chown {{ ansible_env.UID }}:{{ ansible_env.GID }} {{ ansible_env.HOME }}/.kube/config

- name: Copy admin.conf to current directory
  become: yes
  command: cp -i /etc/kubernetes/admin.conf ./

- name: Download Calico manifest
  become: yes
  get_url:
    url: "https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/calico.yaml"
    dest: "calico.yaml"

- name: Apply Calico manifest
  command: kubectl apply -f calico.yaml

- name: Stop kubelet service
  become: yes
  systemd:
    name: kubelet
    state: stopped

- name: Start kubelet service
  become: yes
  systemd:
    name: kubelet
    state: started

